config/routes.rb
Socialteeth7::Application.routes.draw do
  resources :contributions

  devise_for :users

  resources :ads

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ActiveRecord::Base

  belongs_to :user
  has_many :contributions
  
  attr_accessible :title, :user, :description
  
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  
  belongs_to :ad
  belongs_to :user
  
  attr_accessible :user, :ad, :amount
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :ads, :dependent => :destroy
  has_many :contributions
  
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  
  before_filter :authenticate_user!, :except=>[:show, :index]
  
  def index
    @ads = Ad.all
  end

  
  
  def show
    @ad = Ad.find(params[:id])
  end

  
  # GET /ads/new
  def new
    @ad = Ad.new
  end

  
    
  # POST /ads
  def create
	@ad=current_user.ads.build(params[:ad])
	#@ad = Ad.new(params[:ad])
    if @ad.save
      redirect_to @ad, :notice => "Successfully created ad."
    else
      render :action => 'new'
    end
  end
  
  
  
  def edit
    @ad = Ad.find(params[:id])
  end

  
  
  def update
    @ad = Ad.find(params[:id])
    if @ad.update_attributes(params[:ad])
      redirect_to @ad, :notice  => "Successfully updated ad."
    else
      render :action => 'edit'
    end
  end

  
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy
    redirect_to ads_url, :notice => "Successfully destroyed ad."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

  before_filter :authenticate_user!, :except=>[:show, :index]

  def index
    @contributions = Contribution.all
  end

  
  def show
    @contribution = Contribution.find(params[:id])
  end

  
  def new
    @contribution = Contribution.new
  end

  
  def create
    @contribution = current_user.contributions.build(ad_id: params[:contribution][:ad_id], amount: params[:contribution][:amount])
    if @contribution.save
      redirect_to @contribution, :notice => "Successfully created contribution."
    else
      render :action => 'new'
    end
  end

  
  
  def destroy
    @contribution = Contribution.find(params[:id])
    @contribution.destroy
    redirect_to contributions_url, :notice => "Successfully destroyed contribution."
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/ads/_form.html.erb
<%= form_for @ad do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6 %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/ads/edit.html.erb
<% title "Edit Ad" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @ad %> |
  <%= link_to "View All", ads_path %>
</p>

app/views/ads/index.html.erb
<% title "Ads" %>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Description</th>
  </tr>
  <% for ad in @ads %>
    <tr>
      <td><%= ad.title %></td>
      <td><%= ad.user %></td>
      <td><%= ad.description %></td>
      <td><%= link_to "Show", ad %></td>
      <td><%= link_to "Edit", edit_ad_path(ad) %></td>
      <td><%= link_to "Destroy", ad, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Ad", new_ad_path %></p>

app/views/ads/new.html.erb
<% title "New Ad" %>

<%= render 'form' %>

<p><%= link_to "Back to List", ads_path %></p>

app/views/ads/show.html.erb
<% title "Ad" %>

<p>
  <strong>Title:</strong>
  <%= @ad.title %>
</p>
<p>
  <strong>User:</strong>
  <%= @ad.user.email %>
</p>
<p>
  <strong>Description:</strong>
  <%= @ad.description %>
</p>

<%= link_to "Contribute", new_contribution_path(:ad_id=>@ad.id) %>

<p>
  <%= link_to "Edit", edit_ad_path(@ad) %> |
  <%= link_to "Destroy", @ad, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", ads_path %>
</p>

app/views/contributions/_form.html.erb
<%= form_for @contribution do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :ad %><br />
    <%= f.text_field :ad %>
  </p>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/contributions/edit.html.erb
<% title "Edit Contribution" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @contribution %> |
  <%= link_to "View All", contributions_path %>
</p>

app/views/contributions/index.html.erb
<% title "Contributions" %>

<table>
  <tr>
    <th>User</th>
    <th>Ad</th>
    <th>Amount</th>
  </tr>
  <% for contribution in @contributions %>
    <tr>
      <td><%= contribution.user %></td>
      <td><%= contribution.ad %></td>
      <td><%= contribution.amount %></td>
      <td><%= link_to "Show", contribution %></td>
      <td><%= link_to "Destroy", contribution, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Contribution", new_contribution_path %></p>

app/views/contributions/new.html.erb
<% title "New Contribution" %>

<%= form_for @contribution do |f| %>
  <%= f.error_messages %>
  
  <p>
	<%= f.hidden_field :ad, :value=>@ad %>
  </p>
  <p>
    <%= f.label :ad %><br />
    <%= f.text_field :ad %>
  </p>
  <p>
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </p>
  <p><%= f.submit %></p>
<% end %>


<p><%= link_to "Back to List", contributions_path %></p>

app/views/contributions/show.html.erb
<% title "Contribution" %>

<p>
  <strong>User:</strong>
  <%= @contribution.user %>
</p>
<p>
  <strong>Ad:</strong>
  <%= @contribution.ad %>
</p>
<p>
  <strong>Amount:</strong>
  <%= @contribution.amount %>
</p>

<p>
  <%= link_to "Destroy", @contribution, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", contributions_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  
  
  <body>

	  <div id="user_nav">
	  <% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  <% else %>
		<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	  <% end %>
	</div>
  
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
	
	
  </body>
</html>